#!/bin/bash

if [ `id -u` = 0 ];then
	echo "Não pode ser root!"
	exit
fi

RLSET=`readlink -m "$2"`

INSTDIR=`dirname $0`

cd $INSTDIR 
PWDIR=`pwd`

WINEX=wine

WINDIR="$PWDIR/bin"
WINLIB="$PWDIR/lib"
#WINLIB64="$PWDIR/lib64"
GCPMD="$PWDIR/gcmd"
GCPATH="$PWDIR/gchmod"
GCS32="$PWDIR/gchmod/drive_c/windows/system32"
GCDIR="$GCPATH/drive_c/Program Files/Grand Chase History"
GCEXEC="$GCDIR/GrandChase.exe"
GCMEXEC="$GCDIR/main.exe"
WININST=`readlink -m "$0"`


export PATH="$WINDIR:$PATH"
export LD_LIBRARY_PATH="$WINLIB:$LD_LIBRARY_PATH"
#export LD_LIBRARY_PATH="$WINLIB64:$LD_LIBRARY_PATH"
export WINEARCH="win32"
#export WINEARCH="win64"
EXDLL="wmp=n;quartz=n;wmvcore=n;winegstreamer=;devenum=b"

if ( whereis rsync | grep bin ) >> /dev/null ; then
	CPYNC="rsync -dhar --info=progress2"
  else
	CPYNC="cp -u -a -f"
fi

if [ -z "$1" ];then
	export WINEDLLOVERRIDES="$EXDLL"
	export WINEDEBUG="fixme-all,err-all,warn+cursor,-all"
	cd "$GCDIR"
	WINEPREFIX="$GCPATH" "$WINEX" "$GCEXEC"
   else
 case "$1" in
	-cvm|--create-virtual-machine)
	export WINEDEBUG="fixme-all,err-all,warn+cursor,-all"
if [ -d "$GCPATH" ];then
	echo "O path Wine já existe!"
	exit 0
   else
	WINEPREFIX="$GCPATH" winepath
	WINEPREFIX="$GCPATH" winetricks winxp --optout
	#WINEPREFIX="$GCPATH" wine regsvr32 $GCDIR/mailmime.dll (mfc42 = dll dinâmico)
	WINEPREFIX="$GCPATH" winetricks -q dotnet40 --optout

	WINEPREFIX="$GCPATH" winetricks -q mfc42 --optout
	WINEPREFIX="$GCPATH" winetricks -q vcrun6 --optout
	WINEPREFIX="$GCPATH" winetricks -q wmv9vcm --optout
	WINEPREFIX="$GCPATH" winetricks -q quartz --optout

	#WINEPREFIX="$GCPATH" winetricks --force -q dotnet45 --optout
	WINEPREFIX="$GCPATH" winetricks --force -q wmp9 --optout
	WINEPREFIX="$GCPATH" winetricks --force -q allfonts --optout
	WINEPREFIX="$GCPATH" winetricks -q vcrun2015 --optout
	WINEPREFIX="$GCPATH" winetricks --force win7 --optout
	[ -d $GCS32 ] && \
			{
		$CPYNC "$GCS32/quartz.dll" "$GCS32/quartz.dll.old"; # Acertar
		$CPYNC "$GCS32/quartz.dll" "$GCPMD/quartz.dll"; # Acertar
			}
  if [ -d "$GCPATH" ];then
	echo "Máquina virtual criada com sucesso..."
	read -t 5
     else
	echo "Falha ao criar a máquina virtual para o jogo!"
	exit 0
  fi
fi
	exit 0
  ;;
	-d|--debug)
	export WINEDLLOVERRIDES="$EXDLL"
	export WINEDEBUG=""
	cd "$GCDIR"
	WINEPREFIX="$GCPATH" "$WINEX" "$GCEXEC"
  ;;
	# -m|--main)
	#export WINEDEBUG="fixme-all,err-all,warn-cursor,-all"
	#cd "$GCDIR"
	#WINEPREFIX="$GCPATH" "$WINEX" "$GCMEXEC"
  #;;
	# -md|--main-debug)
	#export WINEDEBUG=""
	#cd "$GCDIR"
	#WINEPREFIX="$GCPATH" "$WINEX" "$GCMEXEC"
  #;;
	-i|--install)
   if [ -z "$2" ];then
	echo "Deve escolher o instalador do Grand Chase History para ser instalado!"
	exit 0
   fi
	if [ -d "$GCDIR" ];then
	echo "O Grand Chase History já está instalado!"
	exit 0
		else
	clear
	echo "A instalar o Grand Chase History..."
	read -t 2
	echo "Durante a instalação, DESMARQUE a opção \"Criar um ícone na área de trabalho\"..."
	read -t 3
	echo "Após a instalação, DESMARQUE a opção \"Executar Grand Chase History\"..."
	read -t 3
	echo "Execute o jogo através do ícone criado no menú!"
	read -t 5
	echo "Iniciando o instalador..."
	read -t 3
	export WINEDEBUG="fixme-all,err-all,warn-cursor,-all"
	mkdir -p $GCPATH
	WINEPREFIX="$GCPATH" "$WINEX" "$RLSET"
	#$CPYNC "$GCDIR/NewOption.dat" "$GCDIR/NewOption.dat.old"
	$CPYNC "$PWDIR/gcmd/NewOption.dat" "$GCDIR"
    if [ -d "$GCDIR" ];then
	bash "$0" --fix-shortcuts 
    fi
	fi
  ;;
	-ri|--reinstall)
   if [ -z "$2" ];then
	echo "Deve escolher o instalador do Grand Chase History para ser reinstalado!"
	exit 0
   fi
	if [ -d "$GCDIR" ];then
	echo "A preparar Backup do Grand Chase History..."
	read -t 3
	mkdir -p "$GCPATH/gch_bkp"
	GCHBKP="$GCPATH/gch_bkp"
	echo "Copiando o Grand Chase History para o cache de Backup..."
	$CPYNC "$GCDIR" "$GCHBKP"
	GCHBKPB="$GCHBKP/Grand Chase History"
  if [ -d "$GCHBKPB" ];then
	GCHD=`du -s "$GCDIR" | cut -d "/" -f "1"`
	GCHB=`du -s "$GCHBKPB" | cut -d "/" -f "1"`
   if [ "$GCHD" -eq "$GCHB" ];then
	echo "O Backup foi criado com sucesso!"
	read -t 3
                else
	echo "O Backup não foi criado com sucesso!"
	exit 0
   fi
    else
	echo "O Backup não foi criado com sucesso!"
	exit 0
  fi
	echo "A reinstalar o Grand Chase History..."
	read -t 2
	echo "Durante a reinstalação, DESMARQUE a opção \"Criar um ícone na área de trabalho\"..."
	read -t 5
	echo "Iniciando o instalador..."
	read -t 3
	export WINEDEBUG="fixme-all,err-all,warn-cursor,-all"
	mkdir -p $GCPATH
	WINEPREFIX="$GCPATH" "$WINEX" "$RLSET"
	$CPYNC "$PWDIR/gcmd/NewOption.dat" "$GCDIR"
    if [ -d "$GCDIR" ];then
	bash "$0" --fix-shortcuts 
    fi
		else
	echo "Use a opção {-i|--install} para instalar o Grand Chase History!"
	exit 0
	fi
  ;;
	-rb|--remove-backup)
    GCHBKP="$GCPATH/gch_bkp"
    GCHBKPB="$GCHBKP/Grand Chase History"
if [ -d "$GCHBKPB" ];then
	echo "A excluir o Backup do Grand Chase History..."
	rm -R -f "$GCHBKPB"
  if [ -d "$GCHBKPB" ];then
	echo "O Backup não foi removido!"
	exit 0
		else
	echo "O Backup foi removido com sucesso!"
	exit 0
  fi
    else
	echo "A pasta de Backup do Grand Chase History não existe!"
	exit 0
fi
  ;;
	-re|--restore-backup)
    GCHBKP="$GCPATH/gch_bkp"
    GCHBKPB="$GCHBKP/Grand Chase History"
if [ -d "$GCHBKPB" ];then
	echo "Removendo a instalação atual do Grand Chase History..."
	read -t 3
	rm -R -f $GCDIR
	echo "Restaurando o Backup..."
	$CPYNC "$GCHBKP" "$GCDIR"
  if [ -d "$GCDIR" ];then
	GCHD=`du -s "$GCDIR" | cut -d "/" -f "1"`
	GCHB=`du -s "$GCHBKPB" | cut -d "/" -f "1"`
   if [ "$GCHD" -eq "$GCHB" ];then
	echo "A restauração foi feita com sucesso..."
	read -t 3
	echo "Removendo a pasta de Backup..."
	rm -R -f $GCHBKPB
                else
	echo "A restauração foi quebrada!"
	exit 0
   fi
    else
	echo "A restauração foi quebrada!"
	exit 0
  fi
	else
	echo "Não existe backup a ser restaurado!"
	exit
fi
  ;;
	-f|--fix|--fix-shortcuts)
    SCAPP="$HOME/.local/share/applications"

if [ -e "$SCAPP/GrandChaseHistory.desktop" ];then
##SHORT=Y
if [ -z "$2" ];then
###SHORTGC
	echo "O atalho para o Grand Chase History já existe..."
	read -p "Deseja sobrescrever e atualizar o atalho para \"Grand Chase History\"? (s/N)" SHORTGC
  if [ -z $SHORTGC ];then
	SHORTGC="N"
  fi
###SHORTGC
else
 if [ "$2" = "-y" ];then

	SHORTGC="Y"
     else
  if [ "$2" = "-Y" ];then
	SHORTGC="Y"
    else
	echo "Opção inválida!"
	exit 0
  fi
 fi
fi
##SHORT=Y
  case $SHORTGC in
		n|N|no|No|NO|nO|não|Não|nÂo|nãO)
	echo "O atalho \"Grand Chase History\" será mantido!"
	sleep 3
		;;
		s|S|y|Y|yes|Yes|yEs|yeS|sim|Sim|sIm|siM)
	rm -rf "$SCAPP/GrandChaseHistory.desktop"
	touch "$SCAPP/GrandChaseHistory.desktop"
	echo -e "[Desktop Entry]" >> "$SCAPP/GrandChaseHistory.desktop"
	echo -e "Encoding=UTF-8" >> "$SCAPP/GrandChaseHistory.desktop"
	echo -e "Name="Grand Chase History"" >> "$SCAPP/GrandChaseHistory.desktop"
	echo -e "Comment="Grand Chase History on Linux"" >> "$SCAPP/GrandChaseHistory.desktop"
	echo -e "Type=Application" >> "$SCAPP/GrandChaseHistory.desktop"
	echo "Exec=$WININST" >> "$SCAPP/GrandChaseHistory.desktop"
	echo "Icon="$PWDIR/ico/GrandChase"" >> "$SCAPP/GrandChaseHistory.desktop"
	echo -e "Name[fr_FR]=GrandChase" >> "$SCAPP/GrandChaseHistory.desktop"
	echo -e "Terminal=OFF" >> "$SCAPP/GrandChaseHistory.desktop"
	echo -e "Categories=Game;" >> "$SCAPP/GrandChaseHistory.desktop"
	chmod +x "$SCAPP/GrandChaseHistory.desktop"
	echo "O atalho \"Grand Chase History\" foi atualizado..."
	echo "para acessar, acesse o menú do sistema, na categoria \"Game\"!"
	read -t 3
		;;
		*)
	echo "Opção inválida, digite $0 {-h|--help} para mais informações!"
	exit 0
		;;
  esac
   else
	touch "$SCAPP/GrandChaseHistory.desktop"
	echo -e "[Desktop Entry]" >> "$SCAPP/GrandChaseHistory.desktop"
	echo -e "Encoding=UTF-8" >> "$SCAPP/GrandChaseHistory.desktop"
	echo -e "Name="Grand Chase History"" >> "$SCAPP/GrandChaseHistory.desktop"
	echo -e "Comment="Grand Chase History on Linux"" >> "$SCAPP/GrandChaseHistory.desktop"
	echo -e "Type=Application" >> "$SCAPP/GrandChaseHistory.desktop"
	echo "Exec=$WININST" >> "$SCAPP/GrandChaseHistory.desktop"
	echo "Icon="$PWDIR/ico/GrandChase"" >> "$SCAPP/GrandChaseHistory.desktop"
	echo -e "Name[fr_FR]=GrandChase" >> "$SCAPP/GrandChaseHistory.desktop"
	echo -e "Terminal=OFF" >> "$SCAPP/GrandChaseHistory.desktop"
	echo -e "Categories=Game;" >> "$SCAPP/GrandChaseHistory.desktop"
	chmod +x "$SCAPP/GrandChaseHistory.desktop"

 if [ -e "$SCAPP/GrandChaseHistory.desktop" ];then
	echo "Atalho para o Grand Chase History criado com sucesso"
	echo "Acesse o Menú do sistema, na categoria \"Game\" para abrir o jogo!"
   else
	echo "Falha ao criar o atalho Grand Chase History!"
	exit 0
 fi

fi

#if [ -e "$SCAPP/GrandChaseHistoryMain.desktop" ];then
##SHORT=Y
#if [ -z "$2" ];then
###SHORTGM
	#echo "O atalho para o Grand Chase History Main já existe..."
	#read -p "Deseja sobrescrever e atualizar o atalho para \"Grand Chase History Main\"? (s/N)" SHORTGM
  #if [ -z $SHORTGM ];then
	#SHORTGM="N"
  #fi
###SHORTGM
#else
 #if [ "$2" = "-y" ];then

	#SHORTGM="Y"
     #else
  #if [ "$2" = "-Y" ];then
	#SHORTGM="Y"
    #else
	#echo "Opção inválida!"
	#exit 0
  #fi
 #fi
#fi
##SHORT=Y
  #case $SHORTGM in
	#	n|N|no|No|NO|nO|não|Não|nÂo|nãO)
	#echo "O atalho \"Grand Chase History Main\" será mantido!"
	#sleep 3
		#;;
	#	s|S|y|Y|yes|Yes|yEs|yeS|sim|Sim|sIm|siM)
	#rm -rf "$SCAPP/GrandChaseHistoryMain.desktop"
	#touch "$SCAPP/GrandChaseHistoryMain.desktop"
	#echo -e "[Desktop Entry]" >> "$SCAPP/GrandChaseHistoryMain.desktop"
	#echo -e "Encoding=UTF-8" >> "$SCAPP/GrandChaseHistoryMain.desktop"
	#echo -e "Name="Grand Chase History Main"" >> "$SCAPP/GrandChaseHistoryMain.desktop"
	#echo -e "Comment="Grand Chase History on Linux"" >> "$SCAPP/GrandChaseHistoryMain.desktop"
	#echo -e "Type=Application" >> "$SCAPP/GrandChaseHistoryMain.desktop"
	#echo "Exec=\"$WININST --main\"" >> "$SCAPP/GrandChaseHistoryMain.desktop"
	#echo "Icon="$PWDIR/ico/GrandChaseMain"" >> "$SCAPP/GrandChaseHistoryMain.desktop"
	#echo -e "Name[fr_FR]=GrandChase Main" >> "$SCAPP/GrandChaseHistoryMain.desktop"
	#echo -e "Terminal=OFF" >> "$SCAPP/GrandChaseHistoryMain.desktop"
	#echo -e "Categories=Game;" >> "$SCAPP/GrandChaseHistoryMain.desktop"
	#chmod +x "$SCAPP/GrandChaseHistoryMain.desktop"
	#echo "O atalho \"Grand Chase History Main\" foi atualizado..."
	#echo "Para acessar, acesse o menú do sistema, na categoria \"Game\"!"
	#read -t 3
		#;;
	#	*)
	#echo "Opção inválida, digite $0 {-h|--help} para mais informações!"
	#exit 0
		#;;
  #esac
   #else
	#touch "$SCAPP/GrandChaseHistoryMain.desktop"
	#echo -e "[Desktop Entry]" >> "$SCAPP/GrandChaseHistoryMain.desktop"
	#echo -e "Encoding=UTF-8" >> "$SCAPP/GrandChaseHistoryMain.desktop"
	#echo -e "Name="Grand Chase History Main"" >> "$SCAPP/GrandChaseHistoryMain.desktop"
	#echo -e "Comment="Grand Chase History on Linux"" >> "$SCAPP/GrandChaseHistoryMain.desktop"
	#echo -e "Type=Application" >> "$SCAPP/GrandChaseHistoryMain.desktop"
	#echo "Exec=\"$WININST --main\"" >> "$SCAPP/GrandChaseHistoryMain.desktop"
	#echo "Icon="$PWDIR/ico/GrandChaseMain"" >> "$SCAPP/GrandChaseHistoryMain.desktop"
	#echo -e "Name[fr_FR]=GrandChase Main" >> "$SCAPP/GrandChaseHistoryMain.desktop"
	#echo -e "Terminal=OFF" >> "$SCAPP/GrandChaseHistoryMain.desktop"
	#echo -e "Categories=Game;" >> "$SCAPP/GrandChaseHistoryMain.desktop"
	#chmod +x "$SCAPP/GrandChaseHistoryMain.desktop"

 #if [ -e "$SCAPP/GrandChaseHistoryMain.desktop" ];then
	#echo "Atalho para o Grand Chase History Main criado com sucesso"
	#echo "Acesse o Menú do sistema, na categoria \"Game\" para abrir o jogo!"

   #else
	#echo "Falha ao criar o atalho..."
	#exit 0
 #fi

#fi
	exit 0
  ;;
	-rs|--remove-shortcuts)
    SCAPP="$HOME/.local/share/applications"
if [ -e "$SCAPP/GrandChaseHistory.desktop" ];then
	rm -rf "$SCAPP/GrandChaseHistory.desktop"
  if [ -e "$SCAPP/GrandChaseHistory.desktop" ];then
	echo "O atalho do Grand Chase History não foi removido!"
	exit 0
     else
	echo "O atalho do Grand Chase History foi removido com sucesso!"
  fi
   else
	echo "O atalho para o Grand Chase History não existe ou já foi removido!"
	exit 0
fi

if [ -e "$SCAPP/GrandChaseHistoryMain.desktop" ];then
	rm -rf "$SCAPP/GrandChaseHistoryMain.desktop"
  if [ -e "$SCAPP/GrandChaseHistoryMain.desktop" ];then
	echo "O atalho do Grand Chase History Main não foi removido!"
	exit 0
     else
	echo "O atalho do Grand Chase History Main foi removido com sucesso!"
  fi
   else
	echo "O atalho para o Grand Chase History Main não existe ou já foi removido!"
	exit 0
fi
	exit 0
  ;;
	-rg|--remove-game)
if [ -d "$GCDIR" ];then
	rm -rf "$GCDIR"
 if [ -d "$GCDIR" ];then
	echo "O jogo Grand Chase History não foi removido com exito!"
	exit 0
    else
	echo "O jogo Grand Chase History foi removido com sucesso!"
	bash "$0" --remove-shortcuts
 fi
   else
	echo "O jogo Grand Chase History não existe ou já foi removido!"
	exit 0
fi
  ;;
	-rvm|--remove-virtual-machine)
if [ -d "$GCPATH" ];then
	echo "O jogo Grand Chase History depende da máquina virtual para rodar..."
	echo "Tem certeza que quer remover a máquina virtual?"
	read -p "Digite uma das opções [Sim(S)|Não(N)] : " GCRVM
   case $GCRVM in
		n|N|no|No|NO|nO|não|Não|nÂo|nãO)
	echo "A Máquina Virtual do \"Grand Chase History\" será mantido!"
	sleep 3
		;;
		s|S|y|Y|yes|Yes|yEs|yeS|sim|Sim|sIm|siM)
	echo "Removendo a máquina virtual do Grand Chase History..."
	read -t 3
	rm -rf "$GCPATH"
 if [ -d "$GCPATH" ];then
	echo "A Máquina Virtual do \"Grand Chase History\" foi removido com exito!"
	exit 0
    else
	echo "A Máquina Virtual do \"Grand Chase History\" não foi removido com sucesso!"
 fi
		;;
		*)
	echo "Opção inválida, digite $0 {-h|--help} para mais informações!"
	exit 0
		;;
esac
   else
	echo "A Máquina Virtual do \"Grand Chase History\" não existe ou já foi removido!"
	exit 0
fi
  ;;
  	-wt|--winetricks)
	WINEPREFIX="$GCPATH" winetricks
  ;;
	-xt|--xterm)
	WINEPREFIX="$GCPATH" xterm
  ;;
	-svd|--set-virtual-desktop)
	clear

	VIRTDESKDIM="$2"

	echo -e "Lendo informações do seu monitor:\n"

	read -t 3

	WINEPREFIX="$GCPATH" xrandr

	read -t 3

	echo -e "\nInforme a resolução desejada para a Área de trabalho Virtual..."
	echo -e "Se omitido, será configurado para "1280x1024"..."
	echo -e "Para desativar a àrea de Trabalho Virtual, digite "off" no lugar da resolução.\n"
	read -p "Resolução do Monitor Virtual [ "off" para desativado ] : " VIRTDESKDIM

if [ -z "$VIRTDESKDIM" ];then
	WINEPREFIX="$GCPATH" winetricks vd=off
	read -t 3
	WINEPREFIX="$GCPATH" winetricks vd="1280x1024"
	exit 0
 else
  if [ "$VIRTDESKDIM" = "off" ];then
	WINEPREFIX="$GCPATH" winetricks vd=off
	exit 0
   else
	WINEPREFIX="$GCPATH" winetricks vd="$VIRTDESKDIM"
	exit 0
  fi
fi

  ;;
	-V|--version)
	"$WINEX" --version
	exit 0
  ;;
	-h|--help)
	echo -e '
gcHistory, um aplicativo CLI para ajudar a jogar Grand Chase History em sistemas "não nativos" de sua origem.
Uso: gcHistory [OPÇÃO]... [EXE]...

Argumentos obrigatórios para opções longas também o são para as opções curtas.

	Se omitido, iniciará o jogo via Launcher!


  -h,   --help                         Emite esta ajuda
  -d,   --debug                        Executa o jogo em DEBUG MODE
  -i,   --install {Instalador.exe}     Instala o jogo em seu Usuário Atual
  -ri,  --reinstall  {Instalador.exe}  Faz um Backup do jogo instalado e reinstala por cima
  -rb,  --remove-backup                Remove o Backup criado ao reinstalar o jogo
  -re,  --restore-backup               Remove o jogo reinstalado e restaura o Backup no lugar
  -f,   --fix, --fix-shortcuts         Instala/atualiza um atalho do Launcher e Main no menú do sistema
  -rs,  --remove-shortcuts             Remove o atalho do Launcher e do Main do menú do sistema
  -rg,  --remove-game                  Remove o jogo por completo de seu Usuário Atual
  -wt,  --winetricks                   Abre o configurador Winetricks em modo GUI
  -xt,  --xterm                        Abre o Terminal XTERM usando a máquina virtual do Grand Chase History.
  -cvm, --create-virtual-machine       Cria a Máquina Virtual do Wine para que possa instalar e jogar o Grand Chase History
  -rvm, --remove-virtual-machine       Remove a Máquina Virtual do Wine de forma recursiva. [Cuidado ao usar esta opção]
  -svd, --set-virtual-desktop          Ativa o Desktop Virtual do Wine e configura sua resolução [ off para desativar ]
  -V,  --version                       Mostra a versão do Wine usado e sai
'
	exit 0
  ;;
#Opçoes desativadas:
#  -m,   --main                         Executa o jogo usando o Main em vez do Launcher
#  -md,  --main-debug                   Executa o jogo usando o Main em DEBUG MODE

	*)
	echo -e "\nErro ao completar o comando...\nDigite "$0" {-h|--help} para mais informações!"
	exit 0
	;;
 esac
fi
